### ISSUE TITLE
{% if foo < 1 %} breaks highlighting

### ISSUE THREAD

**Issue by JonCrawford** [tobi/liquid-editor#1]
<code>
{% if foo < 1 %}<br/>
&lt;img src="/foo.jpg" /&gt;<br/>
{% endif %}
</code>

The less-than symbol breaks the syntax highlighting and turns the closing %} tag and the following line red.

**Comment by tobi** [comment]
Have you found a fix for this?

**Comment by axtro** [comment]
I created a quick fix at http://github.com/hennk/liquid-editor/commit/6c75a63ab1bf42d87f012811444f77f3b2fb9bf9 to prevent the xml parser from interpreting '<' as a tag start while in liquid code.
